import "./globals.css";

export const metadata = {
  title:
  {
    default:  "GPS Tracker for Car, Bike, Trucks and Kids | GPS Tracking Software | Free White Label GPS Tracking Platform | Vehicle Tracking System in Pune | Personal GPS Tracker | COSMICA GPS",
    template: '%s | GPS Tracker for Car, Bike, Trucks and Kids | GPS Tracking Software | Free White Label GPS Tracking Platform | Vehicle Tracking System in Pune | Personal GPS Tracker | COSMICA GPS',
  },
   
  description:
    "COSMICA TELEMATICS PVT LTD is specialized in providing Highly Available, Secure White Label GPS tracking Software with multiple GPS device protocols supported. We do provide the complete white label GPS Tracking Platform with latest technologies and framework as per your requirements. We are one stop solution for all kinds of GPS Vehicle Tracking System and GPS Software solution provider in Pune.",
  keywords: [
    "India",
    " best gps tracking company",
    " cosmica gps software",
    "fleet management",
    " gps tracking",
    " gps",
    " gps trackers",
    " gps tracking devices",
    " car tracker",
    " gps car tracking",
    " vehicle tracking",
    " GPS vehicle trackers",
    " bike tracker",
    " children tracker",
    " GPS tracking system",
    " COSMICA gps tracking device",
    " gps tracker devices",
    " gps tracking device in india",
    " gps device tracker",
    " best gps tracker in india",
    " gps tracking device",
    " fleet vehicles tracker",
    " VehicleTracker",
    "Personal GPS Vehicle tracker",
    " Vehicle Tracking Software in Pune",
    " RFID Tracker",
    " Cloud GPS Software",
    " WebSite design and hosting in Pune",
    " Cloud Solution Providers in Pune",
    "top gps tracking company in pune",
    " best gps tracking device provider company",
    "Tracking Application",
    " real time tracking",
    " online free live gps tracking demo in india",
    " car trackers",
    " bike tracker",
    " truck tracker",
    " personal tracker",
    " school bus tracker",
    " vehicle tracker",
    " child tracker",
    " asset tracker",
    " vehicle tracking devices for cars",
    " Static Website Design Companies in Pune",
    " Website Design Companies",
    "Cloud Software providers",
    "Cloud Software providers in Pune",
    " IOT device",
    " IOT GPS device",
    " GPS device manufacturers",
    " Migrate website to cloud",
    " Low cost website design and hosting",
    " Application Development",
    " Android Application development in Pune",
    " iOS Application development in Pune",
    " Best Android Application development in Pune",
    " AWS Cloud solution Consultancy",
    " AWS Cloud solution Consultancy in Pune",
    " Static Website development",
    " Laravel project development",
    " PHP Laravel Development in Pune",
    " PHP website development",
    " Cloud Server hosting in Pune",
    " AWS cloud software development in Pune",
    " SMS API in Pune",
    " SMS Marketing software",
    " Email Marketing Software",
    " Whatsapp Marketing software in Pune",
    " Whatsapp alerts API",
    " AIS 140 GPS tracker in Pune",
    " AIS 140 GPS Tracker in Maharashtra",
    " AIS 140 RTO device",
    "graphic design",
    "web design",
    "web design in Pune",
    "website design",
    "website builder",
    "web application development",
    "ecommerce website",
    " Open Source Technologies",
    "cloud service providers in pune",
    "cloud service providers in India",
    "Vehicle Tracking System in Pune",
    " Vehicle Tracking Dealers in Pune",
    " GPS Device manufacturer in Pune",
    " GPS tracker system",
    " Kids Tracker system",
    "AIS140 IRNSS",
    "Top GPS Companies",
    " Whitelabel GPS Software",
    "White Label GPS Tracking Platform",
    "White Label GPS Tracking Platform in Pune",
    "GPS services in Pune",
    "GPS tracking systems in pune",
    "Vehicle tracking system in pune",
    "GPS services in India",
    "Bharat 101 supplier in Pune",
    "AIS 140 gps suppliers in pune",
    "GPS software services in pune",
    "Indian GPS in Pune",
    "Cosmica GPS in pune",
    "Cosmica services in pune",
    "Indian GPS products in pune",
    "GPS suppliers in pune",
    "GPS distributors in pune",
    "GPS suppliers in Maharashtra",
    "GPS distributors in Maharashtra",
    "GPS distributors in India",
    "On time GPS services in pune",
    "real time GPS services in pune",
    "GPS alert services in pune",
    "Gps Vehicle Tracking System Dealers In Pune",
    "Gps Vehicle Tracking System Dealers In India",
    "Gps Vehicle Tracking System Dealers",
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-0 p-0">{children}</body>
    </html>
  );
}
